[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[program:fastapi]
command=python /code/hf_startup.py
directory=/code
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:discord_bot]
command=sh -c "node init-data.js && node bot.js"
directory=/bot
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DISCORD_TOKEN="%(ENV_DISCORD_TOKEN)s",TARGET_CHANNEL_ID="%(ENV_TARGET_CHANNEL_ID)s"
