"""Add like_count and dislike_count to posts

Revision ID: 3afb2ee70ac7
Revises: 646d70ee1400
Create Date: 2025-07-24 12:08:18.008964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afb2ee70ac7'
down_revision: Union[str, Sequence[str], None] = '646d70ee1400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('dislike_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislike_count')
    op.drop_column('posts', 'like_count')
    # ### end Alembic commands ###
