"""Add comment_reactions table and like/dislike counts to comments

Revision ID: 78d85e4c9f9c
Revises: 33591deca6e8
Create Date: 2025-07-24 14:15:58.645683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d85e4c9f9c'
down_revision: Union[str, Sequence[str], None] = '33591deca6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    reaction_enum = sa.Enum('like', 'dislike', name='reactiontype', create_type=False)
    op.create_table(
        'comment_reactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('reaction', reaction_enum, nullable=False),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'comment_id', name='unique_user_comment')
    )
    op.create_index(op.f('ix_comment_reactions_id'), 'comment_reactions', ['id'], unique=False)
    op.add_column('comments', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('dislike_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'dislike_count')
    op.drop_column('comments', 'like_count')
    op.drop_index(op.f('ix_comment_reactions_id'), table_name='comment_reactions')
    op.drop_table('comment_reactions')
    # ### end Alembic commands ###
